# Generated by Django 4.2.4 on 2023-08-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("length", models.FloatField()),
                ("creator", models.CharField(max_length=255)),
                ("link", models.CharField(max_length=255)),
                ("notes", models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name="task",
            old_name="is_done",
            new_name="done",
        ),
        migrations.AddField(
            model_name="task",
            name="videos",
            field=models.ManyToManyField(to="tasks.video"),
        ),
    ]
