# Generated by Django 4.2.4 on 2023-08-22 09:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_alter_task_videos"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="name",
            new_name="taskName",
        ),
    ]
